import { CvData } from "./cvBuilder";

function uid() { return Math.random().toString(36).slice(2, 9); }

interface RoleContent {
  nameHe: string; nameEn: string;
  titleHe: string; titleEn: string;
  summaryHe: string; summaryEn: string;
  expHe: { role: string; company: string; start: string; end: string; desc: string }[];
  expEn: { role: string; company: string; start: string; end: string; desc: string }[];
  eduHe: { degree: string; school: string; start: string; end: string }[];
  eduEn: { degree: string; school: string; start: string; end: string }[];
  skillsHe: string; skillsEn: string;
  langHe: string; langEn: string;
  milHe: string; milEn: string;
  accent: string;
}

const SAMPLES: Record<string, RoleContent> = {
  "software-engineer": {
    nameHe: "אלון לוי", nameEn: "Alon Levy",
    titleHe: "מהנדס תוכנה בכיר", titleEn: "Senior Software Engineer",
    summaryHe: "מהנדס תוכנה עם 5 שנות ניסיון בפיתוח מערכות Full Stack מורכבות. מתמחה ב-React, Node.js ו-Python, עם ניסיון רב בארכיטקטורת מיקרו-שירותים וסביבות ענן. בוגר אוניברסיטת תל אביב, עם תשוקה לפתרון בעיות מורכבות ומחויבות לאיכות קוד.",
    summaryEn: "Software engineer with 5 years of experience building complex Full Stack systems. Specializes in React, Node.js, and Python, with extensive experience in microservices architecture and cloud environments.",
    expHe: [
      { role: "מהנדס תוכנה בכיר", company: "Monday.com", start: "2022-01", end: "", desc: "פיתוח פיצ'רים מרכזיים בפלטפורמת ניהול העבודה. הובלת ארכיטקטורת מיקרו-שירותים שהגדילה ביצועים ב-40%. מנטורינג לצוות של 4 מפתחים." },
      { role: "מפתח Full Stack", company: "Wix", start: "2019-06", end: "2021-12", desc: "פיתוח רכיבי UI מורכבים ו-APIs לפלטפורמת בניית האתרים. שיפור זמן טעינה ב-35% באמצעות אופטימיזציה ומעבר ל-SSR." },
    ],
    expEn: [
      { role: "Senior Software Engineer", company: "Monday.com", start: "2022-01", end: "", desc: "Led development of core platform features and microservices architecture, improving performance by 40%. Mentored a team of 4 developers." },
      { role: "Full Stack Developer", company: "Wix", start: "2019-06", end: "2021-12", desc: "Built complex UI components and APIs for the website builder platform. Reduced load time by 35% through SSR migration." },
    ],
    eduHe: [{ degree: "תואר ראשון במדעי המחשב", school: "אוניברסיטת תל אביב", start: "2015", end: "2019" }],
    eduEn: [{ degree: "B.Sc. Computer Science", school: "Tel Aviv University", start: "2015", end: "2019" }],
    skillsHe: "React, Node.js, Python, TypeScript, PostgreSQL, Docker, AWS, Redis, GraphQL, Git",
    skillsEn: "React, Node.js, Python, TypeScript, PostgreSQL, Docker, AWS, Redis, GraphQL, Git",
    langHe: "עברית — שפת אם | אנגלית — רמה גבוהה",
    langEn: "Hebrew — Native | English — Fluent",
    milHe: "צבא הגנה לישראל — יחידת 8200, מהנדס תוכנה | 2015–2017",
    milEn: "",
    accent: "#5E6AD2",
  },
  "product-manager": {
    nameHe: "מיכל כהן", nameEn: "Michal Cohen",
    titleHe: "מנהלת מוצר", titleEn: "Product Manager",
    summaryHe: "מנהלת מוצר עם 4 שנות ניסיון בסטארט-אפים ובחברות טכנולוגיה. בעלת חשיבה מוצרית חזקה, ניסיון בניהול רודמאפ ויכולת להוביל צוותים חוצי-ארגוניים. הובלתי השקת 3 מוצרים מה-0 להכנסות של מיליוני דולרים.",
    summaryEn: "Product Manager with 4 years of experience in startups and tech companies. Led 3 product launches from 0 to millions in revenue, with strong data-driven decision making.",
    expHe: [
      { role: "מנהלת מוצר", company: "Fiverr", start: "2021-03", end: "", desc: "ניהול Marketplace Features עבור 3M+ משתמשים. הגדלת ה-GMV ב-28% YoY דרך אופטימיזציה של פאנל ה-onboarding. עבודה צמודה עם R&D, Design ו-Marketing." },
      { role: "PM Junior", company: "IronSource", start: "2019-08", end: "2021-02", desc: "ניהול פיצ'רים בפלטפורמת מינטיזציה של אפליקציות. ביצוע A/B Tests שהגדילו ARPU ב-15%." },
    ],
    expEn: [
      { role: "Product Manager", company: "Fiverr", start: "2021-03", end: "", desc: "Managed marketplace features for 3M+ users. Grew GMV by 28% YoY through onboarding funnel optimization." },
      { role: "Junior PM", company: "IronSource", start: "2019-08", end: "2021-02", desc: "Managed monetization features for mobile apps. A/B tests that increased ARPU by 15%." },
    ],
    eduHe: [{ degree: "תואר ראשון בניהול עסקים", school: "האוניברסיטה העברית", start: "2015", end: "2019" }],
    eduEn: [{ degree: "B.A. Business Administration", school: "Hebrew University", start: "2015", end: "2019" }],
    skillsHe: "Agile, Scrum, JIRA, Figma, SQL, Google Analytics, Mixpanel, Roadmapping, PRD, A/B Testing",
    skillsEn: "Agile, Scrum, JIRA, Figma, SQL, Google Analytics, Mixpanel, Roadmapping, PRD, A/B Testing",
    langHe: "עברית — שפת אם | אנגלית — רמה גבוהה",
    langEn: "Hebrew — Native | English — Fluent",
    milHe: "צבא הגנה לישראל — קצינת מבצעים | 2015–2017",
    milEn: "",
    accent: "#5E6AD2",
  },
  "data-scientist": {
    nameHe: "יוסף אברהם", nameEn: "Yosef Avraham",
    titleHe: "מדען נתונים", titleEn: "Data Scientist",
    summaryHe: "מדען נתונים עם 3 שנות ניסיון בבניית מודלי ML ועיבוד נתונים בסדרי גודל גדולים. ניסיון בניתוח נתונים ופיתוח מוצרי AI בסביבות Production.",
    summaryEn: "Data Scientist with 3 years of experience building ML models and processing large-scale data. Experience in data analysis and AI product development in production environments.",
    expHe: [
      { role: "מדען נתונים", company: "Taboola", start: "2022-01", end: "", desc: "בניית מודלי recommendation המגיעים ל-1B+ אירועים ביום. שיפור CTR ב-12% בעזרת מודל BERT מותאם אישית. שיתוף פעולה עם Engineering להטמעה ב-Production." },
      { role: "אנליסט נתונים", company: "Outbrain", start: "2020-06", end: "2021-12", desc: "ניתוח נתוני קמפיינים פרסומיים ובניית דשבורדים ב-Tableau. זיהוי פאטרנים שחסכו $500K בשנה." },
    ],
    expEn: [
      { role: "Data Scientist", company: "Taboola", start: "2022-01", end: "", desc: "Built recommendation models processing 1B+ daily events. Improved CTR by 12% using a custom BERT model." },
      { role: "Data Analyst", company: "Outbrain", start: "2020-06", end: "2021-12", desc: "Analyzed advertising campaign data and built Tableau dashboards. Identified patterns saving $500K/year." },
    ],
    eduHe: [{ degree: "תואר שני בסטטיסטיקה ומדעי הנתונים", school: "הטכניון", start: "2018", end: "2020" }],
    eduEn: [{ degree: "M.Sc. Statistics & Data Science", school: "Technion", start: "2018", end: "2020" }],
    skillsHe: "Python, SQL, TensorFlow, PyTorch, Scikit-learn, Spark, Airflow, Tableau, R, Azure ML",
    skillsEn: "Python, SQL, TensorFlow, PyTorch, Scikit-learn, Spark, Airflow, Tableau, R, Azure ML",
    langHe: "עברית — שפת אם | אנגלית — רמה גבוהה",
    langEn: "Hebrew — Native | English — Fluent",
    milHe: "צבא הגנה לישראל — יחידה טכנולוגית | 2014–2016",
    milEn: "",
    accent: "#5E6AD2",
  },
  "devops": {
    nameHe: "רועי שמש", nameEn: "Roi Shemesh",
    titleHe: "מהנדס DevOps בכיר", titleEn: "Senior DevOps Engineer",
    summaryHe: "מהנדס DevOps עם 4 שנות ניסיון בבניית תשתיות ענן מדרגיות ואוטומציה של תהליכי CI/CD. מומחה ב-Kubernetes, AWS ו-Terraform.",
    summaryEn: "DevOps Engineer with 4 years of experience building scalable cloud infrastructures and CI/CD automation. Expert in Kubernetes, AWS, and Terraform.",
    expHe: [
      { role: "מהנדס DevOps בכיר", company: "Armis Security", start: "2021-06", end: "", desc: "ניהול תשתית AWS של 200+ שירותים. הפחתת זמן Deploy מ-45 דקות ל-8 דקות. בניית מערכת ניטור כוללת עם Prometheus ו-Grafana." },
      { role: "מהנדס DevOps", company: "Amdocs", start: "2019-09", end: "2021-05", desc: "מעבר של 15 אפליקציות Legacy לקונטיינרים. הטמעת Kubernetes ו-Helm Charts." },
    ],
    expEn: [
      { role: "Senior DevOps Engineer", company: "Armis Security", start: "2021-06", end: "", desc: "Managed AWS infrastructure with 200+ services. Reduced deploy time from 45 to 8 minutes. Built full monitoring with Prometheus & Grafana." },
      { role: "DevOps Engineer", company: "Amdocs", start: "2019-09", end: "2021-05", desc: "Migrated 15 legacy apps to containers. Implemented Kubernetes and Helm Charts." },
    ],
    eduHe: [{ degree: "תואר ראשון בהנדסת מחשבים", school: "אוניברסיטת בן-גוריון", start: "2015", end: "2019" }],
    eduEn: [{ degree: "B.Sc. Computer Engineering", school: "Ben-Gurion University", start: "2015", end: "2019" }],
    skillsHe: "AWS, Kubernetes, Docker, Terraform, CI/CD, Jenkins, GitHub Actions, Prometheus, Grafana, Linux",
    skillsEn: "AWS, Kubernetes, Docker, Terraform, CI/CD, Jenkins, GitHub Actions, Prometheus, Grafana, Linux",
    langHe: "עברית — שפת אם | אנגלית — רמה גבוהה",
    langEn: "Hebrew — Native | English — Fluent",
    milHe: "צבא הגנה לישראל — טכנאי תשתיות | 2015–2017",
    milEn: "",
    accent: "#5E6AD2",
  },
  "qa-engineer": {
    nameHe: "שירה גולן", nameEn: "Shira Golan",
    titleHe: "מהנדסת QA", titleEn: "QA Engineer",
    summaryHe: "מהנדסת QA עם 3 שנות ניסיון באוטומציה ובדיקות ידניות. מתמחה ב-Selenium, Jest ו-Cypress, עם ניסיון בבדיקות API ו-Performance Testing.",
    summaryEn: "QA Engineer with 3 years of experience in automation and manual testing. Specializes in Selenium, Jest, and Cypress, with API and Performance testing experience.",
    expHe: [
      { role: "מהנדסת QA", company: "Varonis", start: "2021-04", end: "", desc: "בניית framework אוטומציה ב-Python/Selenium מאפס. כיסוי של 70% מ-Test Cases ידניים באוטומציה. הפחתת Regression Testing מ-3 ימים לשעתיים." },
      { role: "בוחנת תוכנה", company: "NICE Systems", start: "2019-09", end: "2021-03", desc: "בדיקות ידניות ואוטומציה של מוצרי Analytics. כתיבת Test Plans ו-Bug Reports." },
    ],
    expEn: [
      { role: "QA Engineer", company: "Varonis", start: "2021-04", end: "", desc: "Built Python/Selenium automation framework from scratch. Automated 70% of manual test cases, reducing regression testing from 3 days to 2 hours." },
      { role: "Software Tester", company: "NICE Systems", start: "2019-09", end: "2021-03", desc: "Manual and automated testing of analytics products. Wrote Test Plans and Bug Reports." },
    ],
    eduHe: [{ degree: "תואר ראשון במדעי המחשב", school: "המכללה האקדמית הרצליה", start: "2016", end: "2019" }],
    eduEn: [{ degree: "B.Sc. Computer Science", school: "Reichman University", start: "2016", end: "2019" }],
    skillsHe: "Selenium, Cypress, Jest, Python, Postman, JIRA, SQL, API Testing, Agile, Appium",
    skillsEn: "Selenium, Cypress, Jest, Python, Postman, JIRA, SQL, API Testing, Agile, Appium",
    langHe: "עברית — שפת אם | אנגלית — רמה גבוהה",
    langEn: "Hebrew — Native | English — Fluent",
    milHe: "צבא הגנה לישראל — מ\"פ לוגיסטי | 2014–2016",
    milEn: "",
    accent: "#5E6AD2",
  },
  "fullstack": {
    nameHe: "נועם בן-דוד", nameEn: "Noam Ben-David",
    titleHe: "מפתח Full Stack", titleEn: "Full Stack Developer",
    summaryHe: "מפתח Full Stack עם 4 שנות ניסיון בטכנולוגיות Web מודרניות. בניתי מוצרים מהקצה לקצה — החל מ-UI/UX ועד Databases ו-DevOps.",
    summaryEn: "Full Stack Developer with 4 years of experience building modern web products end-to-end — from UI/UX to databases and DevOps.",
    expHe: [
      { role: "מפתח Full Stack", company: "Elementor", start: "2021-01", end: "", desc: "פיתוח רכיבי עורך Drag-and-Drop ב-React/TypeScript. בניית REST APIs ב-Node.js עם PostgreSQL. תרמתי לשיפור Lighthouse Score ב-20 נקודות." },
      { role: "מפתח Web", company: "Sela Systems", start: "2019-06", end: "2020-12", desc: "פיתוח אתרי E-Commerce ו-CMS ב-Next.js ו-Django. אחריות מלאה על Deploy לסביבות Production." },
    ],
    expEn: [
      { role: "Full Stack Developer", company: "Elementor", start: "2021-01", end: "", desc: "Built drag-and-drop editor components in React/TypeScript. Created REST APIs in Node.js with PostgreSQL. Improved Lighthouse Score by 20 points." },
      { role: "Web Developer", company: "Sela Systems", start: "2019-06", end: "2020-12", desc: "Developed E-Commerce and CMS sites in Next.js and Django. Full ownership of Production deployments." },
    ],
    eduHe: [{ degree: "הנדסאי תוכנה", school: "מכללת HackerU", start: "2017", end: "2019" }],
    eduEn: [{ degree: "Software Engineering Diploma", school: "HackerU College", start: "2017", end: "2019" }],
    skillsHe: "React, Next.js, Node.js, TypeScript, Django, PostgreSQL, MongoDB, Docker, Redis, Git",
    skillsEn: "React, Next.js, Node.js, TypeScript, Django, PostgreSQL, MongoDB, Docker, Redis, Git",
    langHe: "עברית — שפת אם | אנגלית — רמה גבוהה",
    langEn: "Hebrew — Native | English — Fluent",
    milHe: "צבא הגנה לישראל — לוחם גולני | 2014–2016",
    milEn: "",
    accent: "#5E6AD2",
  },
  "marketing-manager": {
    nameHe: "דנה פרידמן", nameEn: "Dana Friedman",
    titleHe: "מנהלת שיווק", titleEn: "Marketing Manager",
    summaryHe: "מנהלת שיווק דיגיטלי עם 6 שנות ניסיון בבניית אסטרטגיות Growth וקמפיינים בתקציבים של מיליוני שקלים. הכפלתי את ה-MQLs ב-3 חברות שונות.",
    summaryEn: "Digital Marketing Manager with 6 years of experience building Growth strategies and campaigns with multi-million budgets. Doubled MQLs across 3 companies.",
    expHe: [
      { role: "מנהלת שיווק דיגיטלי", company: "Walkme", start: "2020-09", end: "", desc: "ניהול תקציב PPC של $2M בחודש. הגדלת MQL ב-80% YoY. הובלת צוות של 5 אנשים. בניית אסטרטגיית SEO שהגדילה Organic Traffic ב-120%." },
      { role: "מנהלת Performance Marketing", company: "Monday.com", start: "2018-03", end: "2020-08", desc: "ניהול קמפיינים ב-Google, Facebook ו-LinkedIn. הפחתת CAC ב-35% תוך הגדלת נפח הלידים." },
    ],
    expEn: [
      { role: "Digital Marketing Manager", company: "Walkme", start: "2020-09", end: "", desc: "Managed $2M monthly PPC budget. Grew MQL by 80% YoY. Led a team of 5. Built SEO strategy increasing organic traffic by 120%." },
      { role: "Performance Marketing Manager", company: "Monday.com", start: "2018-03", end: "2020-08", desc: "Managed Google, Facebook, and LinkedIn campaigns. Reduced CAC by 35% while increasing lead volume." },
    ],
    eduHe: [{ degree: "תואר ראשון בתקשורת ושיווק", school: "אוניברסיטת חיפה", start: "2012", end: "2016" }],
    eduEn: [{ degree: "B.A. Communications & Marketing", school: "University of Haifa", start: "2012", end: "2016" }],
    skillsHe: "Google Ads, Meta Ads, SEO, HubSpot, Salesforce, Google Analytics 4, Semrush, A/B Testing, Email Marketing",
    skillsEn: "Google Ads, Meta Ads, SEO, HubSpot, Salesforce, Google Analytics 4, Semrush, A/B Testing, Email Marketing",
    langHe: "עברית — שפת אם | אנגלית — רמה גבוהה",
    langEn: "Hebrew — Native | English — Fluent",
    milHe: "צבא הגנה לישראל — קצינת קשר | 2011–2013",
    milEn: "",
    accent: "#4ADE80",
  },
  "social-media": {
    nameHe: "תמר ביטון", nameEn: "Tamar Biton",
    titleHe: "מנהלת מדיה חברתית", titleEn: "Social Media Manager",
    summaryHe: "מנהלת מדיה חברתית יצירתית עם 2 שנות ניסיון. בניתי קהילות מעורבות ב-Instagram ו-TikTok עבור מותגי אופנה וטכנולוגיה. מייצרת תוכן ויראלי שמניע תוצאות עסקיות.",
    summaryEn: "Creative Social Media Manager with 2 years of experience. Built engaged communities on Instagram and TikTok for fashion and tech brands.",
    expHe: [
      { role: "מנהלת מדיה חברתית", company: "Renuar Fashion", start: "2023-01", end: "", desc: "גידול של 45K Followers ב-Instagram תוך 8 חודשים. הפקת תוכן ויזואלי יומי. ניהול אינפלואנסרים ו-Brand Collaborations. הגדלת Engagement Rate ב-3.2% ל-6.8%." },
      { role: "מנהלת תוכן", company: "סטארט-אפ FinTech", start: "2022-01", end: "2022-12", desc: "כתיבת תוכן ובניית נוכחות LinkedIn מ-0 ל-8K Followers." },
    ],
    expEn: [
      { role: "Social Media Manager", company: "Renuar Fashion", start: "2023-01", end: "", desc: "Grew Instagram by 45K followers in 8 months. Daily visual content production. Managed influencers and brand collaborations. Grew engagement rate from 3.2% to 6.8%." },
      { role: "Content Manager", company: "FinTech Startup", start: "2022-01", end: "2022-12", desc: "Created content and built LinkedIn presence from 0 to 8K followers." },
    ],
    eduHe: [{ degree: "תואר ראשון בתקשורת", school: "מכללת ספיר", start: "2018", end: "2021" }],
    eduEn: [{ degree: "B.A. Communications", school: "Sapir College", start: "2018", end: "2021" }],
    skillsHe: "Instagram, TikTok, LinkedIn, Canva, Adobe Premiere, Copywriting, Influencer Marketing, Meta Business Suite",
    skillsEn: "Instagram, TikTok, LinkedIn, Canva, Adobe Premiere, Copywriting, Influencer Marketing, Meta Business Suite",
    langHe: "עברית — שפת אם | אנגלית — רמה גבוהה",
    langEn: "Hebrew — Native | English — Fluent",
    milHe: "שירות לאומי — עמותת נוער בסיכון | 2018–2019",
    milEn: "",
    accent: "#4ADE80",
  },
  "content-writer": {
    nameHe: "ליאת אורן", nameEn: "Liat Oren",
    titleHe: "כותבת תוכן ו-SEO", titleEn: "Content Writer & SEO",
    summaryHe: "כותבת תוכן ומומחית SEO עם 3 שנות ניסיון. מתמחה ביצירת תוכן שמניע תנועה אורגנית וממיר קוראים ללקוחות. כתבתי מעל 500 מאמרים עבור מגוון תעשיות.",
    summaryEn: "Content Writer and SEO specialist with 3 years of experience. Specializes in content that drives organic traffic and converts readers to customers.",
    expHe: [
      { role: "מנהלת תוכן ו-SEO", company: "Cynet Security", start: "2022-04", end: "", desc: "הגדלת Organic Traffic ב-200% ב-18 חודשים. כתיבת 40+ מאמרי Blog חודשיים + White Papers. עדכון אסטרטגיית Keywords לפי פרסומי Google." },
      { role: "כותבת תוכן", company: "Fiverr Business", start: "2020-09", end: "2022-03", desc: "כתיבת Case Studies, Email Campaigns ו-Landing Pages. שיפור Open Rate לאימיילים ב-22%." },
    ],
    expEn: [
      { role: "Content & SEO Manager", company: "Cynet Security", start: "2022-04", end: "", desc: "Grew organic traffic by 200% in 18 months. Wrote 40+ monthly blog articles and White Papers." },
      { role: "Content Writer", company: "Fiverr Business", start: "2020-09", end: "2022-03", desc: "Wrote Case Studies, Email Campaigns, and Landing Pages. Improved email open rate by 22%." },
    ],
    eduHe: [{ degree: "תואר ראשון בלשון עברית ותקשורת", school: "אוניברסיטת בר אילן", start: "2016", end: "2020" }],
    eduEn: [{ degree: "B.A. Hebrew Language & Communications", school: "Bar-Ilan University", start: "2016", end: "2020" }],
    skillsHe: "SEO, Semrush, Ahrefs, WordPress, HubSpot, Copywriting, Google Analytics, Email Marketing, Figma",
    skillsEn: "SEO, Semrush, Ahrefs, WordPress, HubSpot, Copywriting, Google Analytics, Email Marketing, Figma",
    langHe: "עברית — שפת אם | אנגלית — רמה גבוהה",
    langEn: "Hebrew — Native | English — Fluent",
    milHe: "",
    milEn: "",
    accent: "#4ADE80",
  },
  "sales-manager": {
    nameHe: "אמיר שפירא", nameEn: "Amir Shapira",
    titleHe: "מנהל מכירות בכיר", titleEn: "Senior Sales Manager",
    summaryHe: "מנהל מכירות B2B עם 5 שנות ניסיון בסגירת עסקאות Enterprise. חריגה מ-Quota ב-130%+ בשלוש שנים רצופות. מנוסה בניהול Pipeline מלא וניהול צוות מכירות.",
    summaryEn: "B2B Sales Manager with 5 years of Enterprise deal closing experience. Exceeded quota by 130%+ for three consecutive years.",
    expHe: [
      { role: "מנהל מכירות בכיר", company: "CyberArk", start: "2021-02", end: "", desc: "ניהול Territory EMEA עם יעד שנתי של $3M. חריגה מ-Quota ב-135% ב-2023. ניהול 4 AEs. סגירת עסקה ב-$800K עם לקוח Fortune 500." },
      { role: "Account Executive", company: "SolarEdge", start: "2018-08", end: "2021-01", desc: "מכירות B2B לחברות אנרגיה סולארית. הגדלת ARR ב-$1.2M תוך שנה." },
    ],
    expEn: [
      { role: "Senior Sales Manager", company: "CyberArk", start: "2021-02", end: "", desc: "Managed EMEA territory with $3M annual target. Exceeded quota by 135% in 2023. Led 4 AEs. Closed $800K deal with Fortune 500 client." },
      { role: "Account Executive", company: "SolarEdge", start: "2018-08", end: "2021-01", desc: "B2B sales to solar energy companies. Grew ARR by $1.2M in one year." },
    ],
    eduHe: [{ degree: "תואר ראשון בכלכלה וניהול", school: "האוניברסיטה הפתוחה", start: "2014", end: "2018" }],
    eduEn: [{ degree: "B.A. Economics & Management", school: "Open University", start: "2014", end: "2018" }],
    skillsHe: "CRM (Salesforce), HubSpot, MEDDIC, Cold Outreach, Pipeline Management, Contract Negotiation, Excel",
    skillsEn: "CRM (Salesforce), HubSpot, MEDDIC, Cold Outreach, Pipeline Management, Contract Negotiation, Excel",
    langHe: "עברית — שפת אם | אנגלית — רמה גבוהה | ספרדית — בסיסי",
    langEn: "Hebrew — Native | English — Fluent | Spanish — Basic",
    milHe: "צבא הגנה לישראל — קצין חי\"ר | 2012–2015",
    milEn: "",
    accent: "#4ADE80",
  },
  "accountant": {
    nameHe: "רחל לוינסון", nameEn: "Rachel Levinson",
    titleHe: "רואת חשבון מוסמכת", titleEn: "Certified Public Accountant",
    summaryHe: "רואת חשבון מוסמכת CPA עם 7 שנות ניסיון בביקורת, דיווח כספי ותכנון מס. ניסיון נרחב עם חברות ציבוריות ופרטיות בתעשיות הייטק ונדל\"ן.",
    summaryEn: "CPA with 7 years of experience in auditing, financial reporting, and tax planning. Extensive experience with public and private companies in tech and real estate.",
    expHe: [
      { role: "מנהלת חשבונות בכירה", company: "רפאל פיתוח אמצעי לחימה", start: "2020-04", end: "", desc: "אחריות על דו\"חות כספיים רבעוניים ושנתיים. ניהול ביקורות חיצוניות. הטמעת מערכת SAP שחסכה 20% מזמן סגירה חודשית." },
      { role: "רואת חשבון", company: "Deloitte Israel", start: "2016-10", end: "2020-03", desc: "ביקורת חברות ציבוריות לפי IFRS. עבודה עם לקוחות Tier-1 בהיקפים של מאות מיליוני שקלים." },
    ],
    expEn: [
      { role: "Senior Accountant", company: "Rafael Advanced Defense Systems", start: "2020-04", end: "", desc: "Responsible for quarterly and annual financial reports. Managed external audits. SAP implementation saving 20% monthly close time." },
      { role: "Accountant", company: "Deloitte Israel", start: "2016-10", end: "2020-03", desc: "Audited public companies under IFRS. Worked with Tier-1 clients with hundreds of millions in revenue." },
    ],
    eduHe: [{ degree: "תואר ראשון בחשבונאות וכלכלה", school: "אוניברסיטת תל אביב", start: "2012", end: "2016" }],
    eduEn: [{ degree: "B.A. Accounting & Economics", school: "Tel Aviv University", start: "2012", end: "2016" }],
    skillsHe: "IFRS, GAAP, SAP, Oracle, Excel מתקדם, דיווח כספי, ביקורת פנים, מס הכנסה, מע\"מ",
    skillsEn: "IFRS, GAAP, SAP, Oracle, Advanced Excel, Financial Reporting, Internal Audit, Tax Planning",
    langHe: "עברית — שפת אם | אנגלית — רמה גבוהה",
    langEn: "Hebrew — Native | English — Fluent",
    milHe: "שירות לאומי — משרד הרווחה | 2010–2012",
    milEn: "",
    accent: "#F59E0B",
  },
  "financial-analyst": {
    nameHe: "גיל מזרחי", nameEn: "Gil Mizrachi",
    titleHe: "אנליסט פיננסי", titleEn: "Financial Analyst",
    summaryHe: "אנליסט פיננסי עם 4 שנות ניסיון בבניית מודלים פיננסיים, הערכות שווי ו-Due Diligence. ניסיון בשוקי הון ו-M&A.",
    summaryEn: "Financial Analyst with 4 years of experience in financial modeling, valuations, and Due Diligence. Experience in capital markets and M&A.",
    expHe: [
      { role: "אנליסט פיננסי בכיר", company: "Bank Hapoalim Capital Markets", start: "2021-06", end: "", desc: "בניית DCF Models ו-Comparable Analysis לחברות ציבוריות. השתתפות ב-5 עסקאות M&A. כתיבת דו\"חות ניתוח למשקיעים מוסדיים." },
      { role: "אנליסט", company: "Discount Capital", start: "2019-09", end: "2021-05", desc: "מחקר מניות בסקטורים תעשייה וטכנולוגיה. בניית מודלים פיננסיים לתמחור IPO." },
    ],
    expEn: [
      { role: "Senior Financial Analyst", company: "Bank Hapoalim Capital Markets", start: "2021-06", end: "", desc: "Built DCF and Comparable Analysis models for public companies. Participated in 5 M&A transactions. Wrote analysis reports for institutional investors." },
      { role: "Analyst", company: "Discount Capital", start: "2019-09", end: "2021-05", desc: "Equity research in industrial and tech sectors. Built financial models for IPO pricing." },
    ],
    eduHe: [{ degree: "תואר ראשון בכלכלה, מנהל עסקים", school: "האוניברסיטה העברית", start: "2015", end: "2019" }],
    eduEn: [{ degree: "B.A. Economics & Business Administration", school: "Hebrew University", start: "2015", end: "2019" }],
    skillsHe: "Excel מתקדם, Bloomberg, DCF, LBO Modeling, Comparable Analysis, PowerPoint, SQL, Python בסיסי",
    skillsEn: "Advanced Excel, Bloomberg, DCF, LBO Modeling, Comparable Analysis, PowerPoint, SQL, Basic Python",
    langHe: "עברית — שפת אם | אנגלית — רמה גבוהה",
    langEn: "Hebrew — Native | English — Fluent",
    milHe: "צבא הגנה לישראל — קצין לוגיסטיקה | 2013–2015",
    milEn: "",
    accent: "#F59E0B",
  },
  "cfo": {
    nameHe: "יעל שטיין", nameEn: "Yael Stein",
    titleHe: "סמנכ\"לית כספים (CFO)", titleEn: "Chief Financial Officer (CFO)",
    summaryHe: "CFO ותיקה עם 12 שנות ניסיון בחברות הייטק ציבוריות ופרטיות. הובלתי 2 IPOs, גיוסי הון של $200M+ וניהול P&L של מאות מיליוני דולרים.",
    summaryEn: "Experienced CFO with 12 years in public and private tech companies. Led 2 IPOs, $200M+ fundraising rounds, and managed P&L of hundreds of millions.",
    expHe: [
      { role: "סמנכ\"לית כספים", company: "Similarweb", start: "2019-01", end: "", desc: "ניהול P&L של $300M+. הובלת תהליך ה-IPO ב-NYSE (2021). בניית תשתית כספית ל-Scale. ניהול צוות פיננסים של 25 עובדים." },
      { role: "VP Finance", company: "CyberArk", start: "2014-06", end: "2018-12", desc: "ניהול תכנון פיננסי ובקרה. תמיכה ב-Series C גיוס של $60M. בניית מחלקת FP&A." },
    ],
    expEn: [
      { role: "CFO", company: "Similarweb", start: "2019-01", end: "", desc: "Managed $300M+ P&L. Led NYSE IPO process (2021). Built financial infrastructure for scale. Managed 25-person finance team." },
      { role: "VP Finance", company: "CyberArk", start: "2014-06", end: "2018-12", desc: "Financial planning and control. Supported Series C $60M raise. Built FP&A department." },
    ],
    eduHe: [{ degree: "תואר שני במנהל עסקים (MBA)", school: "IDC Herzliya", start: "2010", end: "2012" }],
    eduEn: [{ degree: "MBA", school: "Reichman University (IDC)", start: "2010", end: "2012" }],
    skillsHe: "P&L Management, IPO, M&A, FP&A, Board Reporting, Fundraising, SAP, Oracle NetSuite, Excel",
    skillsEn: "P&L Management, IPO, M&A, FP&A, Board Reporting, Fundraising, SAP, Oracle NetSuite, Excel",
    langHe: "עברית — שפת אם | אנגלית — שפת אם | צרפתית — בסיסי",
    langEn: "Hebrew — Native | English — Native | French — Basic",
    milHe: "צבא הגנה לישראל — קצינת מטה | 2000–2003",
    milEn: "",
    accent: "#F59E0B",
  },
  "doctor": {
    nameHe: "ד\"ר אורי גרינברג", nameEn: "Dr. Uri Greenberg",
    titleHe: "רופא מומחה — פנימית", titleEn: "Specialist Physician — Internal Medicine",
    summaryHe: "רופא פנימאי עם 8 שנות ניסיון בבתי חולים ממשלתיים. בוגר הפקולטה לרפואה של האוניברסיטה העברית — הדסה, עם התמחות בקרדיולוגיה.",
    summaryEn: "Internist with 8 years of experience in public hospitals. Graduate of Hebrew University-Hadassah Medical School, with cardiology subspecialty.",
    expHe: [
      { role: "רופא בכיר — מחלקה פנימית", company: "בית חולים שיבא תל השומר", start: "2020-03", end: "", desc: "טיפול שוטף ב-30–40 מטופלים ביום. הדרכת רופאים מתמחים. השתתפות במחקר קליני בנושא אי-ספיקת לב." },
      { role: "רופא מתמחה — פנימית", company: "מרכז רפואי הדסה עין כרם", start: "2016-08", end: "2020-02", desc: "התמחות 4 שנים במחלקה הפנימית. ניסיון בטיפול נמרץ, אוסף אנמנזה, והוצאת נהלים טיפוליים." },
    ],
    expEn: [
      { role: "Senior Physician — Internal Medicine", company: "Sheba Medical Center", start: "2020-03", end: "", desc: "Daily care of 30–40 patients. Teaching and supervising residents. Participating in clinical heart failure research." },
      { role: "Resident — Internal Medicine", company: "Hadassah Ein Kerem Medical Center", start: "2016-08", end: "2020-02", desc: "4-year residency in internal medicine. Experience in intensive care, history taking, and clinical procedures." },
    ],
    eduHe: [
      { degree: "תואר רופא (M.D.)", school: "הפקולטה לרפואה — האוניברסיטה העברית–הדסה", start: "2010", end: "2016" },
    ],
    eduEn: [
      { degree: "Doctor of Medicine (M.D.)", school: "Hebrew University-Hadassah Medical School", start: "2010", end: "2016" },
    ],
    skillsHe: "אבחון קליני, אקו-לב, בדיקת מח עצם, ניהול ICU, ACLS, מחקר קליני, EMR",
    skillsEn: "Clinical diagnosis, Echocardiography, Bone marrow biopsy, ICU management, ACLS, Clinical research, EMR",
    langHe: "עברית — שפת אם | אנגלית — רמה גבוהה | ערבית — בסיסי",
    langEn: "Hebrew — Native | English — Fluent | Arabic — Basic",
    milHe: "צבא הגנה לישראל — רופא שטח, לוחם גולני | 2004–2006",
    milEn: "",
    accent: "#FB7185",
  },
  "nurse": {
    nameHe: "נורית שלום", nameEn: "Nurit Shalom",
    titleHe: "אחות מוסמכת — ICU", titleEn: "Registered Nurse — ICU",
    summaryHe: "אחות מוסמכת עם 5 שנות ניסיון ביחידה לטיפול נמרץ. מומחית בטיפול בחולים קריטיים, עבודה עם מערכות ניטור מתקדמות ותמיכה במשפחות חולים.",
    summaryEn: "Registered Nurse with 5 years of ICU experience. Specialized in critical patient care, advanced monitoring systems, and family support.",
    expHe: [
      { role: "אחות בכירה — יחידה לטיפול נמרץ", company: "מרכז רפואי רמב\"ם", start: "2021-05", end: "", desc: "טיפול ב-3–4 חולים קריטיים במשמרת. אחריות על ניהול תרופות ותיעוד רפואי. הדרכת אחיות חדשות." },
      { role: "אחות — אונקולוגיה", company: "מרכז רפואי שיבא", start: "2019-06", end: "2021-04", desc: "מתן כימותרפיה ותמיכה בחולים ומשפחותיהם. ניהול Port-a-Cath ועירויי דם." },
    ],
    expEn: [
      { role: "Senior Nurse — ICU", company: "Rambam Medical Center", start: "2021-05", end: "", desc: "Cared for 3–4 critically ill patients per shift. Managed medications and clinical documentation. Trained junior nurses." },
      { role: "Nurse — Oncology", company: "Sheba Medical Center", start: "2019-06", end: "2021-04", desc: "Administered chemotherapy and supported patients and families. Managed Port-a-Cath and blood transfusions." },
    ],
    eduHe: [{ degree: "תואר ראשון בסיעוד", school: "בית ספר לסיעוד — הטכניון", start: "2015", end: "2019" }],
    eduEn: [{ degree: "B.Sc. Nursing", school: "Technion School of Nursing", start: "2015", end: "2019" }],
    skillsHe: "ICU, ניטור המודינמי, ACLS, BLS, מתן כימותרפיה, ניהול תרופות, EMR (Ofek)",
    skillsEn: "ICU, Hemodynamic monitoring, ACLS, BLS, Chemotherapy administration, Medication management, EMR",
    langHe: "עברית — שפת אם | אנגלית — רמה טובה | רוסית — שפת אם",
    langEn: "Hebrew — Native | English — Good | Russian — Native",
    milHe: "שירות לאומי — קופת חולים מאוחדת | 2013–2015",
    milEn: "",
    accent: "#FB7185",
  },
  "physiotherapist": {
    nameHe: "עידן ברקוביץ", nameEn: "Idan Berkowitz",
    titleHe: "פיזיותרפיסט קליני", titleEn: "Clinical Physiotherapist",
    summaryHe: "פיזיותרפיסט עם 4 שנות ניסיון בשיקום אורתופדי, ספורט ועמוד שדרה. עבדתי עם ספורטאים מקצועיים וחולים לאחר ניתוחים. מוסמך McKenzie ו-PNF.",
    summaryEn: "Physiotherapist with 4 years of experience in orthopedic, sports, and spine rehabilitation. Worked with professional athletes and post-surgical patients. Certified McKenzie & PNF.",
    expHe: [
      { role: "פיזיותרפיסט בכיר", company: "מרפאת Sport-Med תל אביב", start: "2021-09", end: "", desc: "טיפול ב-10–12 מטופלים ביום. התמחות בפציעות ספורט וחזרה לפעילות. ליווי ספורטאי הפועל תל אביב." },
      { role: "פיזיותרפיסט", company: "בית חולים אסף הרופא", start: "2019-11", end: "2021-08", desc: "שיקום לאחר ניתוחי ברך וירך. עבודה בצוות רב-מקצועי." },
    ],
    expEn: [
      { role: "Senior Physiotherapist", company: "Sport-Med Clinic Tel Aviv", start: "2021-09", end: "", desc: "Treated 10–12 patients daily. Specialized in sports injuries and return-to-play. Supported Hapoel Tel Aviv athletes." },
      { role: "Physiotherapist", company: "Assaf Harofeh Hospital", start: "2019-11", end: "2021-08", desc: "Post-surgical knee and hip rehabilitation. Worked in multidisciplinary teams." },
    ],
    eduHe: [{ degree: "תואר ראשון בפיזיותרפיה", school: "אוניברסיטת תל אביב", start: "2015", end: "2019" }],
    eduEn: [{ degree: "B.PT. Physiotherapy", school: "Tel Aviv University", start: "2015", end: "2019" }],
    skillsHe: "שיקום אורתופדי, פיזיותרפיית ספורט, עמוד שדרה, מניפולציות, McKenzie, PNF, Pilates קליני, דיקור",
    skillsEn: "Orthopedic rehabilitation, Sports physiotherapy, Spine, Manipulations, McKenzie, PNF, Clinical Pilates, Dry needling",
    langHe: "עברית — שפת אם | אנגלית — רמה גבוהה",
    langEn: "Hebrew — Native | English — Fluent",
    milHe: "צבא הגנה לישראל — פיזיותרפיסט צבאי | 2013–2015",
    milEn: "",
    accent: "#FB7185",
  },
  "teacher": {
    nameHe: "מרים אביב", nameEn: "Miriam Aviv",
    titleHe: "מורה לחינוך מיוחד ומתמטיקה", titleEn: "Special Education & Math Teacher",
    summaryHe: "מורה ותיקה עם 6 שנות ניסיון בהוראה בחינוך הרגיל והמיוחד. מתמחה במתמטיקה לכיתות ז'–י\"ב עם דגש על למידה חוויתית ותמיכה בתלמידים עם לקויות למידה.",
    summaryEn: "Experienced teacher with 6 years in regular and special education. Specializes in mathematics for grades 7–12 with experiential learning and learning disability support.",
    expHe: [
      { role: "מורה למתמטיקה ורכזת שכבה", company: "בית ספר תיכון עירוני א' — תל אביב", start: "2020-09", end: "", desc: "הוראת מתמטיקה ל-5 כיתות ז'–ט'. שיפור ממוצע הבגרות ב-12 נקודות. ריכוז שכבת ז' — 180 תלמידים." },
      { role: "מורה לחינוך מיוחד", company: "בית ספר מיוחד \"אופק\" — ירושלים", start: "2018-09", end: "2020-06", desc: "הוראה בכיתות קטנות לילדים עם אוטיזם ולקויות למידה. בניית תוכניות לימוד אישיות (IEP)." },
    ],
    expEn: [
      { role: "Math Teacher & Grade Coordinator", company: "Municipal High School Tel Aviv", start: "2020-09", end: "", desc: "Taught mathematics to 5 classes (grades 7–9). Improved bagrut average by 12 points. Coordinated grade 7 — 180 students." },
      { role: "Special Education Teacher", company: "\"Ofek\" Special School Jerusalem", start: "2018-09", end: "2020-06", desc: "Taught small classes with autism and learning disabilities. Developed individual education plans (IEP)." },
    ],
    eduHe: [
      { degree: "תואר שני בחינוך מיוחד", school: "אוניברסיטת בר אילן", start: "2018", end: "2020" },
      { degree: "תואר ראשון במתמטיקה וחינוך", school: "הקולג' האקדמי בית ברל", start: "2014", end: "2018" },
    ],
    eduEn: [
      { degree: "M.Ed. Special Education", school: "Bar-Ilan University", start: "2018", end: "2020" },
      { degree: "B.Ed. Mathematics & Education", school: "Beit Berl Academic College", start: "2014", end: "2018" },
    ],
    skillsHe: "הוראה דיפרנציאלית, IEP, לקויות למידה, מתמטיקה, Excel חינוכי, Zoom Teaching, ניהול כיתה",
    skillsEn: "Differentiated instruction, IEP, Learning disabilities, Mathematics, Google Classroom, Zoom, Classroom management",
    langHe: "עברית — שפת אם | אנגלית — רמה טובה",
    langEn: "Hebrew — Native | English — Good",
    milHe: "שירות לאומי — עמותת אלו\"ט | 2012–2014",
    milEn: "",
    accent: "#34D399",
  },
  "principal": {
    nameHe: "ד\"ר חיים פרץ", nameEn: "Dr. Haim Peretz",
    titleHe: "מנהל בית ספר", titleEn: "School Principal",
    summaryHe: "מנהל בית ספר תיכון עם 10 שנות ניסיון בניהול חינוכי ופדגוגי. הובלתי שיפור משמעותי בתוצאות הבגרות ופיתוח תרבות בית-ספרית חיובית.",
    summaryEn: "High school principal with 10 years of educational and pedagogical leadership. Led significant improvements in matriculation results and school culture.",
    expHe: [
      { role: "מנהל בית ספר תיכון", company: "תיכון \"שקמה\" — אשדוד", start: "2018-09", end: "", desc: "ניהול 800 תלמידים ו-60 מורים. שיפור אחוז זכאות לבגרות מ-68% ל-81%. הקמת מסלול הייטק בשיתוף עם חברות טכנולוגיה." },
      { role: "סגן מנהל", company: "תיכון \"אורט\" — ראשון לציון", start: "2014-09", end: "2018-08", desc: "ניהול פדגוגי של מגמות ריאליות. ריכוז פרויקטי חינוך ייחודיים. הדרכת מורים." },
    ],
    expEn: [
      { role: "High School Principal", company: "\"Shikma\" High School, Ashdod", start: "2018-09", end: "", desc: "Managed 800 students and 60 teachers. Improved matriculation rate from 68% to 81%. Launched a tech track in partnership with tech companies." },
      { role: "Vice Principal", company: "\"ORT\" High School, Rishon LeZion", start: "2014-09", end: "2018-08", desc: "Pedagogical management of science tracks. Coordinated special education projects. Teacher training." },
    ],
    eduHe: [
      { degree: "דוקטורט בחינוך", school: "אוניברסיטת חיפה", start: "2015", end: "2019" },
      { degree: "תואר שני בניהול חינוכי", school: "אוניברסיטת בן-גוריון", start: "2010", end: "2013" },
    ],
    eduEn: [
      { degree: "Ph.D. Education", school: "University of Haifa", start: "2015", end: "2019" },
      { degree: "M.Ed. Educational Management", school: "Ben-Gurion University", start: "2010", end: "2013" },
    ],
    skillsHe: "ניהול חינוכי, פדגוגיה, תקצוב, גיוס עובדים, הדרכת מורים, תהליכי בגרות, עבודה קהילתית",
    skillsEn: "Educational management, Pedagogy, Budgeting, Staff recruitment, Teacher training, Matriculation processes, Community work",
    langHe: "עברית — שפת אם | אנגלית — רמה גבוהה",
    langEn: "Hebrew — Native | English — Fluent",
    milHe: "צבא הגנה לישראל — קצין חינוך | 1996–1999",
    milEn: "",
    accent: "#34D399",
  },
  "lecturer": {
    nameHe: "פרופ' שרה כץ", nameEn: "Prof. Sarah Katz",
    titleHe: "מרצה וחוקרת — פסיכולוגיה", titleEn: "Lecturer & Researcher — Psychology",
    summaryHe: "מרצה בכירה בפסיכולוגיה חברתית באוניברסיטת בר-אילן עם 8 שנות ניסיון במחקר ובהוראה. פרסמתי 14 מאמרים בכתבי עת מובילים ואני חוקרת ראשית במענק EU של €500K.",
    summaryEn: "Senior Psychology lecturer at Bar-Ilan University with 8 years in research and teaching. Published 14 papers in leading journals, leading PI on a €500K EU grant.",
    expHe: [
      { role: "מרצה בכירה", company: "אוניברסיטת בר-אילן — מחלקת פסיכולוגיה", start: "2019-10", end: "", desc: "הוראת 3 קורסים סמסטריאליים ל-200+ סטודנטים. פרסום 8 מאמרים ב-5 שנים. הדרכת 6 סטודנטים לתואר שני." },
      { role: "עמיתת מחקר", company: "הטכניון — מרכז למדעי קוגניטיביים", start: "2016-10", end: "2019-09", desc: "ניהול פרויקטי מחקר במימון ISF. פרסום 6 מאמרים ב-peer-reviewed journals." },
    ],
    expEn: [
      { role: "Senior Lecturer", company: "Bar-Ilan University — Psychology Department", start: "2019-10", end: "", desc: "Teaching 3 semester courses to 200+ students. Published 8 papers in 5 years. Supervised 6 graduate students." },
      { role: "Research Fellow", company: "Technion — Cognitive Science Center", start: "2016-10", end: "2019-09", desc: "Led ISF-funded research projects. Published 6 peer-reviewed journal articles." },
    ],
    eduHe: [
      { degree: "דוקטורט בפסיכולוגיה", school: "אוניברסיטת תל אביב", start: "2012", end: "2016" },
    ],
    eduEn: [
      { degree: "Ph.D. Psychology", school: "Tel Aviv University", start: "2012", end: "2016" },
    ],
    skillsHe: "SPSS, R, מחקר איכותני וכמותני, כתיבה אקדמית, ניהול מענקים, Python, הוראה בשיטה הסוקרטית",
    skillsEn: "SPSS, R, Qualitative & Quantitative research, Academic writing, Grant management, Python, Socratic teaching",
    langHe: "עברית — שפת אם | אנגלית — רמה גבוהה | צרפתית — בסיסי",
    langEn: "Hebrew — Native | English — Fluent | French — Basic",
    milHe: "שירות לאומי | 2003–2004",
    milEn: "",
    accent: "#34D399",
  },
  "project-manager": {
    nameHe: "בני שפרן", nameEn: "Benny Shapran",
    titleHe: "מנהל פרויקטים PMP", titleEn: "Project Manager PMP",
    summaryHe: "מנהל פרויקטים מוסמך PMP עם 6 שנות ניסיון בניהול פרויקטי IT מורכבים. ניהלתי פרויקטים בתקציבים של עד $5M עם צוותים חוצי-גבולות.",
    summaryEn: "PMP-certified Project Manager with 6 years managing complex IT projects up to $5M with cross-border teams.",
    expHe: [
      { role: "מנהל פרויקטים בכיר", company: "Amdocs", start: "2020-06", end: "", desc: "ניהול פרויקטי Transformation טלקומוניקציה בתקציב $3M. ניהול Stakeholders במספר מדינות. Delivery ב-On-Time ועל תקציב ב-95% מהפרויקטים." },
      { role: "מנהל פרויקטים", company: "Ness Technologies", start: "2017-09", end: "2020-05", desc: "ניהול 3–5 פרויקטים במקביל. הטמעת Agile ו-SAFe בצוותים של 15+ חברים." },
    ],
    expEn: [
      { role: "Senior Project Manager", company: "Amdocs", start: "2020-06", end: "", desc: "Managed telecom transformation projects with $3M budget. Multi-country stakeholder management. 95% on-time, on-budget delivery rate." },
      { role: "Project Manager", company: "Ness Technologies", start: "2017-09", end: "2020-05", desc: "Managed 3–5 concurrent projects. Implemented Agile and SAFe with 15+ member teams." },
    ],
    eduHe: [{ degree: "תואר ראשון בהנדסת תעשייה וניהול", school: "הטכניון", start: "2013", end: "2017" }],
    eduEn: [{ degree: "B.Sc. Industrial Engineering & Management", school: "Technion", start: "2013", end: "2017" }],
    skillsHe: "PMP, Agile, Scrum, SAFe, Jira, MS Project, Stakeholder Management, Risk Management, Excel",
    skillsEn: "PMP, Agile, Scrum, SAFe, Jira, MS Project, Stakeholder Management, Risk Management, Excel",
    langHe: "עברית — שפת אם | אנגלית — רמה גבוהה",
    langEn: "Hebrew — Native | English — Fluent",
    milHe: "צבא הגנה לישראל — קצין מבצעים | 2010–2013",
    milEn: "",
    accent: "#818CF8",
  },
  "operations": {
    nameHe: "טל פינקלשטיין", nameEn: "Tal Finkelstein",
    titleHe: "מנהל תפעול", titleEn: "Operations Manager",
    summaryHe: "מנהל תפעול עם 7 שנות ניסיון בבניית תהליכים, שרשרת אספקה ו-KPIs. הובלתי תהליכי Scale-Up שאפשרו גידול של 3X בהכנסות ללא גידול פרופורציונלי בכוח האדם.",
    summaryEn: "Operations Manager with 7 years in process building, supply chain, and KPIs. Led scale-up processes enabling 3X revenue growth without proportional headcount growth.",
    expHe: [
      { role: "מנהל תפעול", company: "XM Cyber", start: "2019-07", end: "", desc: "בניית תשתית תפעולית ל-Scale מ-50 ל-300 עובדים. הטמעת ERP (NetSuite). ניהול Vendor Relations ורכש בהיקף $8M." },
      { role: "מנהל לוגיסטיקה", company: "Solbar Industries", start: "2016-04", end: "2019-06", desc: "ניהול שרשרת אספקה גלובלית. הפחתת Lead Time ב-30% ועלויות לוגיסטיות ב-18%." },
    ],
    expEn: [
      { role: "Operations Manager", company: "XM Cyber", start: "2019-07", end: "", desc: "Built operational infrastructure for scale from 50 to 300 employees. Implemented NetSuite ERP. Managed vendor relations and $8M procurement." },
      { role: "Logistics Manager", company: "Solbar Industries", start: "2016-04", end: "2019-06", desc: "Managed global supply chain. Reduced lead time by 30% and logistics costs by 18%." },
    ],
    eduHe: [{ degree: "תואר ראשון בניהול לוגיסטי", school: "מכון טכנולוגי חולון (HIT)", start: "2012", end: "2016" }],
    eduEn: [{ degree: "B.Sc. Logistics Management", school: "Holon Institute of Technology (HIT)", start: "2012", end: "2016" }],
    skillsHe: "ERP (NetSuite, SAP), Supply Chain, KPIs, Lean, Six Sigma, Excel, Vendor Management, Procurement",
    skillsEn: "ERP (NetSuite, SAP), Supply Chain, KPIs, Lean, Six Sigma, Excel, Vendor Management, Procurement",
    langHe: "עברית — שפת אם | אנגלית — רמה גבוהה",
    langEn: "Hebrew — Native | English — Fluent",
    milHe: "צבא הגנה לישראל — קצין לוגיסטיקה בכיר | 2009–2012",
    milEn: "",
    accent: "#818CF8",
  },
  "ceo": {
    nameHe: "דוד אלבז", nameEn: "David Elbaz",
    titleHe: "מנכ\"ל", titleEn: "Chief Executive Officer",
    summaryHe: "מנכ\"ל סדרתי עם 15 שנות ניסיון בבניית ויישום אסטרטגיה עסקית. הובלתי 2 חברות ל-Exit: אחת ב-$120M (2018) ואחת ב-$380M (2023). בוגר Wharton MBA.",
    summaryEn: "Serial CEO with 15 years of experience building and executing business strategy. Led 2 company exits: $120M (2018) and $380M (2023). Wharton MBA graduate.",
    expHe: [
      { role: "מנכ\"ל ומייסד שותף", company: "Veridian AI (נרכשה על ידי Salesforce)", start: "2019-01", end: "2023-12", desc: "בניית חברת AI מהקמה עד Exit של $380M. גיוס $45M B2. גידול ARR מ-$0 ל-$22M. בניית צוות של 120 עובדים ב-4 שנים." },
      { role: "מנכ\"ל", company: "CloudSafe (נרכשה על ידי Akamai)", start: "2014-03", end: "2018-11", desc: "הובלת Exit של $120M. גיוס $18M, בניית ערוצי מכירה ב-12 מדינות." },
    ],
    expEn: [
      { role: "CEO & Co-Founder", company: "Veridian AI (acquired by Salesforce)", start: "2019-01", end: "2023-12", desc: "Built AI company from 0 to $380M exit. Raised $45M Series B. Grew ARR from $0 to $22M. Built a team of 120 in 4 years." },
      { role: "CEO", company: "CloudSafe (acquired by Akamai)", start: "2014-03", end: "2018-11", desc: "Led $120M exit. Raised $18M, built sales channels across 12 countries." },
    ],
    eduHe: [{ degree: "MBA — The Wharton School, University of Pennsylvania", school: "University of Pennsylvania", start: "2007", end: "2009" }],
    eduEn: [{ degree: "MBA — The Wharton School, University of Pennsylvania", school: "University of Pennsylvania", start: "2007", end: "2009" }],
    skillsHe: "אסטרטגיה עסקית, M&A, גיוס הון (VC), Board Management, Sales, Marketing, Hiring, P&L",
    skillsEn: "Business strategy, M&A, VC fundraising, Board management, Sales, Marketing, Hiring, P&L",
    langHe: "עברית — שפת אם | אנגלית — שפת אם",
    langEn: "Hebrew — Native | English — Native",
    milHe: "צבא הגנה לישראל — קצין מודיעין | 1997–2000",
    milEn: "",
    accent: "#818CF8",
  },
  "ux-designer": {
    nameHe: "מאיה דהן", nameEn: "Maya Dahan",
    titleHe: "מעצבת UX/UI", titleEn: "UX/UI Designer",
    summaryHe: "מעצבת UX/UI עם 4 שנות ניסיון בעיצוב מוצרים דיגיטליים. מומחית ב-Figma, מחקר משתמשים ו-Design Systems. עבדתי על מוצרים עם מיליוני משתמשים.",
    summaryEn: "UX/UI Designer with 4 years of experience in digital product design. Expert in Figma, user research, and Design Systems. Worked on products with millions of users.",
    expHe: [
      { role: "מעצבת UX/UI בכירה", company: "Wix", start: "2021-04", end: "", desc: "עיצוב תהליכי Onboarding לאתרי העסק. הגדלת Completion Rate ב-28% לאחר Redesign. בניית Design System עם 200+ קומפוננטות. עבודה צמודה עם PM ו-Engineering." },
      { role: "מעצבת UX", company: "Elementor", start: "2019-08", end: "2021-03", desc: "עיצוב ממשקי עורך ו-Widgets. ביצוע User Testing ו-A/B Testing על 500K+ משתמשים." },
    ],
    expEn: [
      { role: "Senior UX/UI Designer", company: "Wix", start: "2021-04", end: "", desc: "Designed business site onboarding flows. Increased completion rate by 28% post-redesign. Built Design System with 200+ components." },
      { role: "UX Designer", company: "Elementor", start: "2019-08", end: "2021-03", desc: "Designed editor interfaces and widgets. Conducted User Testing and A/B Testing for 500K+ users." },
    ],
    eduHe: [{ degree: "תואר ראשון בעיצוב תקשורת חזותית", school: "בצלאל — האקדמיה לאמנות ועיצוב", start: "2015", end: "2019" }],
    eduEn: [{ degree: "B.Des. Visual Communication Design", school: "Bezalel Academy of Arts & Design", start: "2015", end: "2019" }],
    skillsHe: "Figma, Adobe XD, Principle, Maze, Miro, Prototyping, User Research, Design Systems, HTML/CSS בסיסי",
    skillsEn: "Figma, Adobe XD, Principle, Maze, Miro, Prototyping, User Research, Design Systems, Basic HTML/CSS",
    langHe: "עברית — שפת אם | אנגלית — רמה גבוהה",
    langEn: "Hebrew — Native | English — Fluent",
    milHe: "שירות לאומי — עמותת יד שרה | 2013–2014",
    milEn: "",
    accent: "#A78BFA",
  },
  "graphic-designer": {
    nameHe: "שי אברמוביץ", nameEn: "Shai Abramowitz",
    titleHe: "מעצב גרפי ו-Brand", titleEn: "Graphic Designer & Brand",
    summaryHe: "מעצב גרפי עם 5 שנות ניסיון בבניית זהויות מותג, חומרי שיווק ועיצוב דיגיטלי. עבדתי עם מותגים ישראלים ובינלאומיים בתחומי אופנה, טכנולוגיה ונדל\"ן.",
    summaryEn: "Graphic Designer with 5 years of experience in brand identity, marketing materials, and digital design. Worked with Israeli and international brands in fashion, tech, and real estate.",
    expHe: [
      { role: "מעצב גרפי בכיר", company: "McCann Tel Aviv", start: "2020-11", end: "", desc: "עיצוב קמפיינים ללקוחות Tier-1: Strauss, Partner, Leumi. עיצוב זהויות מותג ומערכות חזותיות מלאות. ניהול 3 דיזיינרים זוטרים." },
      { role: "מעצב גרפי", company: "Freelance", start: "2018-06", end: "2020-10", desc: "עיצוב לוגואים, עיצוב דיגיטלי ו-Print לעסקים קטנים ובינוניים. 50+ פרויקטים בשנה." },
    ],
    expEn: [
      { role: "Senior Graphic Designer", company: "McCann Tel Aviv", start: "2020-11", end: "", desc: "Designed campaigns for Tier-1 clients: Strauss, Partner, Leumi. Created brand identities and complete visual systems. Managed 3 junior designers." },
      { role: "Graphic Designer", company: "Freelance", start: "2018-06", end: "2020-10", desc: "Logo design, digital, and print design for SMBs. 50+ projects per year." },
    ],
    eduHe: [{ degree: "תואר ראשון בעיצוב גרפי", school: "המכון הטכנולוגי חולון (HIT)", start: "2014", end: "2018" }],
    eduEn: [{ degree: "B.Des. Graphic Design", school: "Holon Institute of Technology (HIT)", start: "2014", end: "2018" }],
    skillsHe: "Adobe Illustrator, Photoshop, InDesign, After Effects, Figma, Brand Identity, Typography, Print Design",
    skillsEn: "Adobe Illustrator, Photoshop, InDesign, After Effects, Figma, Brand Identity, Typography, Print Design",
    langHe: "עברית — שפת אם | אנגלית — רמה טובה",
    langEn: "Hebrew — Native | English — Good",
    milHe: "צבא הגנה לישראל — מעצב גרפי, דובר צה\"ל | 2012–2014",
    milEn: "",
    accent: "#A78BFA",
  },
  "lawyer": {
    nameHe: "עו\"ד נטע גרינשטיין", nameEn: "Adv. Neta Greenstein",
    titleHe: "עורכת דין — דיני מסחר ו-M&A", titleEn: "Attorney — Commercial Law & M&A",
    summaryHe: "עורכת דין עם 8 שנות ניסיון בדיני מסחר, M&A וחוזים מורכבים. ניסיון נרחב בייצוג חברות הייטק ישראליות בעסקאות בינלאומיות.",
    summaryEn: "Attorney with 8 years of experience in commercial law, M&A, and complex contracts. Extensive experience representing Israeli tech companies in international transactions.",
    expHe: [
      { role: "שותפה מנהלת — דין מסחרי", company: "שרון–גרינשטיין ושות'", start: "2020-01", end: "", desc: "ניהול תיקי M&A בהיקפים של עשרות מיליוני דולרים. ייצוג חברות טכנולוגיה בעסקאות בינלאומיות. ניהול צוות של 5 עורכי דין." },
      { role: "עורכת דין בכירה", company: "Gross, Kleinhendler, Hodak, Halevy (GKH)", start: "2016-10", end: "2019-12", desc: "עבודה על IPOs, עסקאות M&A, הסכמי שותפות וחוזים מורכבים בשווי $1B+." },
    ],
    expEn: [
      { role: "Managing Partner — Commercial Law", company: "Sharon-Greenstein & Co.", start: "2020-01", end: "", desc: "Managed M&A cases worth tens of millions of dollars. Represented tech companies in international deals. Led a team of 5 attorneys." },
      { role: "Senior Attorney", company: "GKH Law", start: "2016-10", end: "2019-12", desc: "Worked on IPOs, M&A transactions, partnership agreements, and $1B+ complex contracts." },
    ],
    eduHe: [
      { degree: "תואר ראשון במשפטים LL.B.", school: "אוניברסיטת תל אביב", start: "2010", end: "2014" },
    ],
    eduEn: [
      { degree: "LL.B. Law", school: "Tel Aviv University", start: "2010", end: "2014" },
    ],
    skillsHe: "דיני מסחר, M&A, חוזים, Due Diligence, ליטיגציה מסחרית, IP, הגנת פרטיות (GDPR), משא ומתן",
    skillsEn: "Commercial law, M&A, Contracts, Due Diligence, Commercial litigation, IP, GDPR, Negotiation",
    langHe: "עברית — שפת אם | אנגלית — שפת אם",
    langEn: "Hebrew — Native | English — Native",
    milHe: "שירות לאומי | 2008–2010",
    milEn: "",
    accent: "#60A5FA",
  },
  "legal-advisor": {
    nameHe: "עו\"ד גדי כהן", nameEn: "Adv. Gadi Cohen",
    titleHe: "יועץ משפטי פנימי", titleEn: "In-House Legal Counsel",
    summaryHe: "יועץ משפטי עם 6 שנות ניסיון בסביבה תאגידית. מתמחה ברגולציה, IP, פרטיות נתונים וניהול סיכונים משפטיים עבור חברות SaaS.",
    summaryEn: "Legal Counsel with 6 years of corporate experience. Specializes in regulation, IP, data privacy, and legal risk management for SaaS companies.",
    expHe: [
      { role: "יועץ משפטי בכיר", company: "Gong.io", start: "2021-01", end: "", desc: "ניהול כל ההיבטים המשפטיים של חברה SaaS B2B עם $100M+ ARR. כתיבת 200+ חוזים בשנה. ניהול תהליכי GDPR ו-SOC2." },
      { role: "עורך דין", company: "Herzog Fox & Neeman", start: "2017-10", end: "2020-12", desc: "ייצוג בעסקאות הון-סיכון ו-M&A. ניסיון ב-Term Sheets ו-SHA." },
    ],
    expEn: [
      { role: "Senior Legal Counsel", company: "Gong.io", start: "2021-01", end: "", desc: "Managed all legal aspects of a $100M+ ARR SaaS company. Drafted 200+ contracts per year. Led GDPR and SOC2 processes." },
      { role: "Attorney", company: "Herzog Fox & Neeman", start: "2017-10", end: "2020-12", desc: "Represented VC and M&A transactions. Experience with Term Sheets and SHA." },
    ],
    eduHe: [{ degree: "תואר ראשון במשפטים LL.B.", school: "האוניברסיטה העברית", start: "2012", end: "2016" }],
    eduEn: [{ degree: "LL.B. Law", school: "Hebrew University", start: "2012", end: "2016" }],
    skillsHe: "GDPR, IP, חוזים מסחריים, Term Sheet, Due Diligence, SaaS, רגולציה, ניהול סיכונים",
    skillsEn: "GDPR, IP, Commercial contracts, Term Sheet, Due Diligence, SaaS, Regulation, Risk management",
    langHe: "עברית — שפת אם | אנגלית — שפת אם",
    langEn: "Hebrew — Native | English — Native",
    milHe: "צבא הגנה לישראל — קצין משפטי | 2010–2013",
    milEn: "",
    accent: "#60A5FA",
  },
  "hr-manager": {
    nameHe: "נועה שגב", nameEn: "Noa Segev",
    titleHe: "מנהלת משאבי אנוש", titleEn: "HR Manager",
    summaryHe: "מנהלת HR עם 5 שנות ניסיון בחברות הייטק. מתמחה בגיוס, תגמול, L&D ובניית תרבות ארגונית. ניהלתי תהליכי Scale מ-50 ל-300 עובדים.",
    summaryEn: "HR Manager with 5 years in tech companies. Specializes in recruitment, compensation, L&D, and culture building. Led scale processes from 50 to 300 employees.",
    expHe: [
      { role: "מנהלת HR", company: "ControlUp", start: "2021-03", end: "", desc: "ניהול מחזור חיים מלא של עובד — גיוס, Onboarding, ביצועים ו-Exit. הובלת מעבר ממדיניות תגמול לא-אחידה ל-Band System. הגדרת ערכי תרבות ארגונית." },
      { role: "Talent Acquisition Manager", company: "Papaya Global", start: "2018-09", end: "2021-02", desc: "גיוס 80+ עובדים בשנה בתפקידים טכניים ועסקיים. הטמעת ATS (Greenhouse). Time-to-Hire ירד מ-52 ל-30 יום." },
    ],
    expEn: [
      { role: "HR Manager", company: "ControlUp", start: "2021-03", end: "", desc: "Managed full employee lifecycle — recruitment, onboarding, performance, and exit. Led transition from ad-hoc comp to Band System. Defined organizational culture values." },
      { role: "Talent Acquisition Manager", company: "Papaya Global", start: "2018-09", end: "2021-02", desc: "Recruited 80+ employees per year in technical and business roles. Implemented Greenhouse ATS. Reduced time-to-hire from 52 to 30 days." },
    ],
    eduHe: [{ degree: "תואר ראשון בפסיכולוגיה ארגונית", school: "אוניברסיטת חיפה", start: "2014", end: "2018" }],
    eduEn: [{ degree: "B.A. Organizational Psychology", school: "University of Haifa", start: "2014", end: "2018" }],
    skillsHe: "גיוס, Greenhouse, Compensation & Benefits, L&D, HRIS (HiBob), Performance Management, Employee Relations",
    skillsEn: "Recruitment, Greenhouse, Compensation & Benefits, L&D, HRIS (HiBob), Performance Management, Employee Relations",
    langHe: "עברית — שפת אם | אנגלית — רמה גבוהה",
    langEn: "Hebrew — Native | English — Fluent",
    milHe: "צבא הגנה לישראל — קצינת משאבי אנוש | 2012–2014",
    milEn: "",
    accent: "#F472B6",
  },
  "recruiter": {
    nameHe: "עומר לוי", nameEn: "Omer Levi",
    titleHe: "מגייס טכנולוגי", titleEn: "Tech Recruiter",
    summaryHe: "מגייס טכנולוגי עם 3 שנות ניסיון בגיוס מהנדסים ומנהלי מוצר לחברות הייטק. מתמחה ב-Sourcing יצירתי ו-LinkedIn Recruiting.",
    summaryEn: "Tech Recruiter with 3 years of experience recruiting engineers and PMs for tech companies. Specializes in creative sourcing and LinkedIn Recruiting.",
    expHe: [
      { role: "מגייס טכנולוגי", company: "WalkMe", start: "2022-02", end: "", desc: "גיוס 40+ מהנדסים ו-PMs בשנה. Sourcing יצירתי דרך LinkedIn, GitHub ו-Stack Overflow. Time-to-Fill ממוצע 28 יום. הקמת Employer Branding ב-LinkedIn." },
      { role: "מגייס", company: "SDR Recruiting", start: "2020-09", end: "2022-01", desc: "גיוס לחברות הייטק ישראליות מגדולות. 60+ Placements בשנה." },
    ],
    expEn: [
      { role: "Tech Recruiter", company: "WalkMe", start: "2022-02", end: "", desc: "Recruited 40+ engineers and PMs per year. Creative sourcing via LinkedIn, GitHub, and Stack Overflow. Average 28-day time-to-fill. Built LinkedIn Employer Branding." },
      { role: "Recruiter", company: "SDR Recruiting", start: "2020-09", end: "2022-01", desc: "Recruited for leading Israeli tech companies. 60+ placements per year." },
    ],
    eduHe: [{ degree: "תואר ראשון בפסיכולוגיה", school: "אוניברסיטת בן-גוריון", start: "2016", end: "2020" }],
    eduEn: [{ degree: "B.A. Psychology", school: "Ben-Gurion University", start: "2016", end: "2020" }],
    skillsHe: "LinkedIn Recruiter, Greenhouse, Sourcing, Behavioral Interviews, Employer Branding, ATS, Boolean Search",
    skillsEn: "LinkedIn Recruiter, Greenhouse, Sourcing, Behavioral Interviews, Employer Branding, ATS, Boolean Search",
    langHe: "עברית — שפת אם | אנגלית — רמה גבוהה",
    langEn: "Hebrew — Native | English — Fluent",
    milHe: "צבא הגנה לישראל — לוחם | 2014–2016",
    milEn: "",
    accent: "#F472B6",
  },
};

export function getSampleCv(roleId: string, lang: "he" | "en"): CvData | null {
  const s = SAMPLES[roleId];
  if (!s) return null;

  const isHe = lang === "he";

  const experiences = (isHe ? s.expHe : s.expEn).map((e) => ({
    id: uid(),
    role: e.role,
    company: e.company,
    location: isHe ? "ישראל" : "Israel",
    start: e.start,
    end: e.end,
    current: !e.end,
    description: e.desc,
  }));

  const educations = (isHe ? s.eduHe : s.eduEn).map((e) => ({
    id: uid(),
    degree: e.degree,
    school: e.school,
    location: isHe ? "ישראל" : "Israel",
    start: e.start,
    end: e.end,
    current: false,
    description: "",
  }));

  const mil = isHe && s.milHe
    ? (() => {
        const parts = s.milHe.split(" | ");
        const timeParts = (parts[1] ?? "").split("–");
        return {
          unit: parts[0] ?? "",
          role: "",
          start: timeParts[0]?.trim() ?? "",
          end: timeParts[1]?.trim() ?? "",
          reserveDuty: false,
        };
      })()
    : { unit: "", role: "", start: "", end: "", reserveDuty: false };

  return {
    personal: {
      fullName: isHe ? s.nameHe : s.nameEn,
      title: isHe ? s.titleHe : s.titleEn,
      email: `${s.nameEn.split(" ")[0].toLowerCase()}@example.com`,
      phone: "050-000-0000",
      location: isHe ? "תל אביב, ישראל" : "Tel Aviv, Israel",
      linkedin: `linkedin.com/in/${s.nameEn.split(" ")[0].toLowerCase()}`,
      website: "",
      photo: "",
    },
    summary: isHe ? s.summaryHe : s.summaryEn,
    experiences,
    educations,
    military: mil,
    skills: isHe ? s.skillsHe : s.skillsEn,
    languages: isHe ? s.langHe : s.langEn,
    volunteering: "",
    template: "slate",
    accentColor: s.accent,
  };
}
